--- 
language: ruby
env: 
  global: 
  - PUBLISHER_LOGIN=seteam
  - secure: |-
      sAsO5q3khbk3/kHNixmwEWif5sd4DM5/BAEO2CwhUP812Kkh9iWqb+ksfE5D
      Ce++PEPrKnWDDwjmcH1xa82uCo+5zfmNZQfsR65N03zeIBNvvbsHP94rnN6a
      zaIA5kE8DeO8DCSQa2nYvLSx0R/UX9SIl3zq7MA7CoG5C6e4swo=
script: 
- git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng
- .forge-releng/publish
branches: 
  only: 
  - master
